# Automation to send push notification if water leak is detected under kitchen sink.

alias: Kitchen Water Leak Notification
description: ""
trigger:
  - type: moist
    platform: device
    device_id: 48e82b1e662b91fc6ac8a4873a15d614
    entity_id: binary_sensor.lumi_lumi_sensor_wleak_aq1_ias_zone
    domain: binary_sensor
condition: []
action:
  - service: notify.mobile_app_jimbo
    data:
      message: Water leak kitchen sink
      title: Kitchen sink water leak
mode: single
