# Automation to detect and alert if a door has been acidently left open.

alias: Notify Side Door Left Open
description: send ping to Jim’s phone when side door opened
trigger:
  - platform: state
    entity_id: binary_sensor.lumi_lumi_sensor_magnet_aq2_on_off
    from: "off"
    to: "on"
    for:
      hours: 0
      minutes: 2
      seconds: 0
condition: []
action:
  - service: notify.mobile_app_iphone
    data:
      message: Side door left open
      title: Side door open
  - service: tts.google_translate_say
    data:
      entity_id: media_player.downstairs_speakers
      message: Side door has been left open
      cache: false
mode: single
